apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: monitoring
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: monitoring-app
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
